### ISSUE TITLE
For project details, click Service Endpoint, page 403

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#103]
项目详情点击Service Endpoint 和 service slow endpoint，页面403
![image](https://user-images.githubusercontent.com/95004531/212339322-96ac5061-4114-4d13-bacc-9bffb2cb6029.png)
![image](https://user-images.githubusercontent.com/95004531/212339365-de8ed058-e54c-4582-bfe8-ab9759822489.png)

**Comment by Qinyouzeng** [comment]
@15168440402 endpoint list 跳转评估下，不好实现先移除
