### ISSUE TITLE
The application selects DCC to display the data of the Scheduler

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#107]
应用选择DCC，显示Scheduler的数据
![image](https://user-images.githubusercontent.com/95004531/212344044-286f049b-deab-40db-85f0-038ac7f48b84.png)

**Comment by Qinyouzeng** [comment]
这个数据目前如此，当前实际展示数据为：dcc服务调用过的api地址，根据服务划分各自的api,当前还无法满足
