### ISSUE TITLE
Description The type of a new dashboard is incorrect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#109]
新建仪表盘，类型数据不对
![image](https://user-images.githubusercontent.com/95004531/212457521-d66929d3-c89c-450f-bddc-50d4d99e8f60.png)
![image](https://user-images.githubusercontent.com/95004531/212457529-5c541886-9337-4a35-b346-6f5c4197c35e.png)

**Comment by Qinyouzeng** [comment]
环境不一致，保持全部是Staging
