### ISSUE TITLE
Dashboard, Edit Echarts component, right Settings option expanded, UI style adjustment

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#120]
仪表盘，编辑Echarts组件，右侧设置选项展开后，页面出现滚动条，穿透顶部栏，且左侧区域空白。需调整样式
![image](https://user-images.githubusercontent.com/95004531/212464855-f45c5365-a8d8-4553-a03a-540ad355a7f7.png)

**Comment by 15168440402** [comment]
@xie1wei2 顶部栏是否需要穿透

**Comment by MayueCif** [comment]
可以修改为中间部分固定左侧部分滚动

**Comment by xie1wei2** [comment]
顶部固定，不需要穿透。这个感觉相当奇怪。
