### ISSUE TITLE
Service success rate data is incorrect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#156]
服务成功率数据不正确
![image](https://user-images.githubusercontent.com/95004531/223004660-0652c979-5ce8-4e57-9322-086a8bf8aea9.png)
![image](https://user-images.githubusercontent.com/95004531/223004722-94ca8e17-4e3c-440a-aedf-959e8b1e354e.png)

**Comment by Qinyouzeng** [comment]
数据问题，需要排查
