### ISSUE TITLE
TSC时间选择器组件修改（全局统一）

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#163]
![image](https://user-images.githubusercontent.com/101324746/224207090-89e0f177-9c8f-40e0-aae2-1a46c01f5439.png)

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

1.24小时制（非AM、PM、上午、下午）
--
2.时区+8 增加tooltips，注释
3.时间组件全局I18N没有支持
4.时区选择，是可搜索的Autcomplete
5.时分秒选择前，应当定位在目前的时间上（时、分为主）
6.最近24小时后面还有一个-关闭-需要去掉
7.自动刷新下拉，1个小时、2个小时，去掉个字

</body>

</html>

**Comment by doddgu** [comment]
@LazyEar0 PTAL
