### ISSUE TITLE
TSC 团队首页问题修改

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#164]
![image](https://user-images.githubusercontent.com/101324746/224207983-34ebb683-0cc7-4b93-96f4-d61c5a86f213.png)

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

1.右侧卡片点击背景不是一个整体，需要修改为一个整体效果
--
2.右侧卡片为单选，默认选中第一个（没有不可能选中状态）
3.鼠标悬浮至对应六边形，六边形会有一个悬浮效果（稍微凸起变大）同时六边形中的应用程序也有鼠标悬停效果。可以点击进入应用详情

</body>

</html>

**Comment by xie1wei2** [comment]
点击六边形非应用区域跳转项目详情与应用详情一致（默认第一个应用程序）

**Comment by doddgu** [comment]
@LazyEar0 PTAL

**Comment by xie1wei2** [comment]
![image](https://user-images.githubusercontent.com/101324746/225217308-cbd55c81-4943-4d87-abf6-d92284f61a23.png)
还原原型中的卡片名称
