### ISSUE TITLE
TSC 项目/应用详情页问题修改

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#165]
![image](https://user-images.githubusercontent.com/101324746/224210097-b2e1874a-7b72-425b-b3d5-9c112ecf4d60.png)
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

1.页面还原效果差，应用ID有文字描述确实（其他还原效果需要对照UI设计稿还原，不作过多解释）
--
2.指标名称需要有I18N支持
3.服务成功率指标-图表为还原
4.服务负载图表未还原（鼠标悬停后缺失名称）
5.如果通过应用点击进入，左上角有默认选中的应用，如点击项目进入则显示项目中第一个应用程序（现在为空，指标数据哪来的）
6.服务平均响应时间-单位重复（根据UI设计稿）只保留一个单位
7.服务端负载/服务缓负载未还原设计稿（时间再后）并且可以点击对应缓的程序并通过TraceID搜索跳转至对应内容，取最大值（非平均值）
8.应用详情页面缺失（见设计稿）

</body>

</html>

**Comment by xie1wei2** [comment]
补充：左侧项目与应用详情也需要还原设计稿效果
另外需增加日志报错（后续见设计稿）

**Comment by doddgu** [comment]
@LazyEar0 PTAL
