### ISSUE TITLE
TSC图表编辑问题修改

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#167]
![image](https://user-images.githubusercontent.com/101324746/224217362-c4e3d61a-4b6a-4df6-8843-f437e0ce9c97.png)
![image](https://user-images.githubusercontent.com/101324746/224217402-7b32fd45-dd12-4a08-8d82-0e34ac7b5610.png)
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

1.图表需要增加时间选择器组件（全局统一）
--
2.图一指标卡片修改-指标名称修改可下拉可输入表达式的框，去掉取值范围，图表参考Auth权限添加Icon
3.图二指标卡片修改-指标名称修改为名称/取值范围修改可下拉可输入表达式的框（Autcomplete），计算规则去掉，选择颜色需要补充上

</body>

</html>

**Comment by doddgu** [comment]
@LazyEar0 PTAL
