### ISSUE TITLE
The time selector does not have i18n

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#182]
时间选择器没有i18n
![image](https://user-images.githubusercontent.com/95004531/226502947-0a9a58d0-3d2c-473d-a2e8-b81ac1b9eccb.png)

**Comment by kogel-net** [comment]
已经由闫鹏举在组件库中解决此问题

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by LazyEar0** [comment]
> 已经由闫鹏举在组件库中解决此问题

@codding-y   解决完毕后将此问题标记resolved

**Comment by Qinyouzeng** [comment]
时区选择，数据源为主机系统读取的时区选项信息，依赖主机的Culture配置；如通过需要i18n支持，可能需要手动维护时区信息

**Comment by Qinyouzeng** [comment]
时区选择，数据源为主机系统读取的时区选项信息，依赖主机的Culture配置；如通过需要i18n支持，可能需要手动维护时区信息
此问题不是时间选择器组件问题
