### ISSUE TITLE
Project team, click more application button has no response

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#183]
项目团队，点击更多应用按钮无反应
![image](https://user-images.githubusercontent.com/95004531/226504083-ac314690-09c0-49ef-b7b9-24f5a3b93a3a.png)
预期效果：
应打开项目详情弹窗，默认选中第一个应用

**Comment by Qinyouzeng** [comment]
已修复，验证中

**Comment by Qinyouzeng** [comment]
已修复
