### ISSUE TITLE
The time selector, when opened again, does not automatically position itself to show the number

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#184]
时间选择器，再次打开时分秒下拉框，没有自动定位到显示数字的地方

https://user-images.githubusercontent.com/95004531/226504556-b9d10186-31d9-4054-93c4-a45796e11471.mp4

**Comment by wuweilaiya** [comment]
masa blazo issues：https://github.com/masastack/MASA.Blazor/issues/1249
