### ISSUE TITLE
Project details, the automatic refresh of the time selector should be brought in from the project team list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#186]
1.项目团队设置自动刷新时间为10s
![image](https://user-images.githubusercontent.com/95004531/226506056-2bb08272-48ca-47c7-93a3-5afe585ae35f.png)
2.打开项目详情弹窗
实际结果：
项目详情中时间选择器的自动刷新时间为关闭
![image](https://user-images.githubusercontent.com/95004531/226506089-0a556024-ffdf-49ae-aa73-e60fa5853a79.png)
预期结果：
打开项目详情时，时间选择器的自动刷新时间应从项目团队列表中带入

**Comment by Qinyouzeng** [comment]
未处理，可分配

**Comment by xie1wei2** [comment]
目前时间区间只提供当前最近30天的数据，日期时间区间为最近30天时间可选择。
在团队页面，日志页面，追踪页面设置完时间区间，刷新时间以后会自动带到相对应的内页中。

**Comment by binwan-dev** [comment]
已解决项目团队到应用详情弹出框
