### ISSUE TITLE
Project team, project display error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#187]
项目团队，项目应显示：
1.关联当前登录用户所选择团队的项目
2.上报tsc的项目
![image](https://user-images.githubusercontent.com/95004531/226524313-e858adbe-4889-4428-ae3e-0cef0f774ef4.png)
现显示所有上报tsc的项目，没有过滤所选团队

**Comment by Qinyouzeng** [comment]
已修复，验证中

**Comment by Qinyouzeng** [comment]
已修复
