### ISSUE TITLE
Chart data is not displayed by time zone

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#189]
图表数据没有根据时区显示，最近12小时数据，横坐标应显示 2023.3.21 01:36 ~ 2023.3.21 13.36 的数据
![image](https://user-images.githubusercontent.com/95004531/226526603-02b17366-1c03-448b-9838-8f4d964f0d72.png)

**Comment by Qinyouzeng** [comment]
已修复，验证中

**Comment by Qinyouzeng** [comment]
已修复
