### ISSUE TITLE
When the service success rate is 100%, a white line is displayed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#191]
服务成功率100%时，显示一条白线
实际效果：
![image](https://user-images.githubusercontent.com/95004531/226527378-126f8ae0-f0af-4ed0-b245-53edba6e209e.png)
预期效果：
![image](https://user-images.githubusercontent.com/95004531/226528762-847cdc04-915c-441a-81ea-2b7ec9460a7c.png)

**Comment by Qinyouzeng** [comment]
ui 配置问题，设计图，两种颜色中间有空白间隙，只有一种数据时，需要去掉空白间隙
可分配
