### ISSUE TITLE
If the service success rate is decimal, reserve two decimal places.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#192]
服务成功率如有小数时，四舍五入保留两位小数。
如 99.994%，则显示99.99%
99.995%，则显示100%
![image](https://user-images.githubusercontent.com/95004531/226529088-b043e056-b212-47e6-93f2-a069b105e76f.png)

**Comment by LazyEar0** [comment]
.net 默认四舍五入计算方法为国际会计标准，遇5奇数进，偶数不进，以取整为例：1.5 四舍五入为2，2.5 四舍五入为2
此处的四舍五入为中国的会计标准，即逢五就进一，逢四就舍。

**Comment by Qinyouzeng** [comment]
需要配置echart 饼图的 百分比显示配置函数，按照要求配置即可，目前是默认计算和展示
可分配
