### ISSUE TITLE
The number of error logs should be queried and changed based on the time selected by the time selector

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#193]
错误日志条数，应根据时间选择器所选的时间查询并发生变化，现仅固定显示为刚进入项目详情时的日志条数
![image](https://user-images.githubusercontent.com/95004531/226529646-dd280bc6-add6-4d59-abb5-e27baebc485f.png)

**Comment by MapleWithoutWords** [comment]
![image](https://user-images.githubusercontent.com/38368335/227181261-4cd51478-fa58-44e5-b868-1c26f1e95189.png)
已被修改

**Comment by Qinyouzeng** [comment]
已修复，验证中
