### ISSUE TITLE
Service satisfaction chart style error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#195]
服务满意度图表样式错误
实际结果：
![image](https://user-images.githubusercontent.com/95004531/226531664-afa1303f-0838-4afb-a819-4a2a4dc9cbf0.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/226531889-9f498526-7fcf-4ca7-847f-59cebaaa4af1.png)

**Comment by Qinyouzeng** [comment]
样式配置实际应该和效果图是一致，因为数据原因，无法展现出效果图的效果，可复查下，
展示数据：Apdex 变化率 ，例如：[{time:1,data:90.09 },{time:2,data:89},{time:3,data:99}]，展示的数据为：[{time:2,data: 89-90.09},{time:3,data: 99-89}], 显示的数据为Apdex的变化过程，右上角为当前最新的变化值
指标表达式，可以从代码代码找到，或者代码调试时查看实际的指标表达式，查询的 [promethues] (http://192.168.10.98/9090)
可分配
