### ISSUE TITLE
To apply the details page, remove the View Edit button

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#197]
应用详情页，应去掉查看编辑按钮
![image](https://user-images.githubusercontent.com/95004531/226534940-3d805f22-99ed-4bb1-92cf-d58aedfc4069.png)

**Comment by wuweilaiya** [comment]
这个页面是可以编辑的吧

**Comment by LazyEar0** [comment]
@xie1wei2 确认一下这个页面是否需要编辑按钮

**Comment by xie1wei2** [comment]
编辑按钮隐藏，这个页面不主张用户修改！更不可以删除。编辑按钮隐藏掉，位置保留。不放别的内容。
