### ISSUE TITLE
Apply the details page and a double scroll bar appears

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#198]
应用详情页，出现了双滚动条
![image](https://user-images.githubusercontent.com/95004531/226535930-a3e7c2ee-0dfd-4f01-a2da-77fe34fa52c8.png)

**Comment by LazyEar0** [comment]
@xie1wei2 请确认需求

**Comment by xie1wei2** [comment]
在编辑模式状态下可能出现双滚动条，非编辑模式状态下很少可能出现。具体需要固定大小，默认大小正好适合页面，减少一个滚动条。
