### ISSUE TITLE
Project details Click to view application details, you should enter the application details page in the pop-up window

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#200]
项目详情点击查看应用详情，应在弹窗中进入应用详情页。现为页面
![image](https://user-images.githubusercontent.com/95004531/226536286-7eb56647-e2f9-4021-bc06-ef422ef090b6.png)
![image](https://user-images.githubusercontent.com/95004531/226536415-a4b89a13-2954-483a-acea-63515f478913.png)

**Comment by wuweilaiya** [comment]
需求就是打开新页面的

**Comment by LazyEar0** [comment]
@xie1wei2  请确认需求

**Comment by wuweilaiya** [comment]
现在rc1就是打开新页面，今天谢伟出了个弹窗里移动页面的需求，不过是rc2开发的,这个应该不算bug，或者应该移到rc2

**Comment by LazyEar0** [comment]
@xie1wei2 请确认需求

**Comment by xie1wei2** [comment]
c1就先保持这个效果，不做变更了。c2再进行变更。
