### ISSUE TITLE
Application details The indicators should be shown as required

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#201]
应用详情各项指标应根据需求显示图表
实际效果
![image](https://user-images.githubusercontent.com/95004531/226536593-d5086fbf-b347-42aa-9a24-159e8a4e9f08.png)
预期效果
![image](https://user-images.githubusercontent.com/95004531/226537731-56c8e320-ac1f-46e3-bffc-fdf58391dc40.png)

**Comment by Qinyouzeng** [comment]
无需功能调整，数据重新打开编辑保存后，可恢复正常

**Comment by Qinyouzeng** [comment]
数据目前同 种子数据的Service 仪表盘，设计图的实际图标数据不做参考

**Comment by LazyEar0** [comment]
数据的问题导致图表没有显示

**Comment by Qinyouzeng** [comment]
参见 #207
