### ISSUE TITLE
Click API invalid

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#202]
点击API无效
![image](https://user-images.githubusercontent.com/95004531/226538268-4eed0cad-16d2-40fc-b007-443cd01e718c.png)

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/227093746-02710c47-809c-477d-abc6-3016d9d4b43b.png)

**Comment by Qinyouzeng** [comment]
这个只有团弹框的页面，慢接口列表可以弹出trace相详情页面，接口已经添加，Gateway 的TraceSerivce 里面，具体分配联系@wuleilai
