### ISSUE TITLE
For details about the project, view the details of the error Log, jump to log, and search criteria will be automatically entered in the search

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#203]
项目详情，查看错误日志详情，跳转至Log，搜索中应自动带入搜索条件
![image](https://user-images.githubusercontent.com/95004531/226538561-dcc9d112-22bb-49be-9b37-87cbf5d000ff.png)

![image](https://user-images.githubusercontent.com/95004531/226538498-2e84e7da-1f1b-4aee-9a4f-4eb3e84375b9.png)

**Comment by Qinyouzeng** [comment]
显示为 es 查询表达式

**Comment by Qinyouzeng** [comment]
可分配，如果吴自浩有时间，可以让他来处理，alert有过类似处理

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/229009926-12025249-cc9a-46db-91d1-26de74569ee1.png)
