### ISSUE TITLE
Average service response time. The maximum value is not fully displayed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#204]
服务平均响应时间，最大值显示不全
![image](https://user-images.githubusercontent.com/95004531/226539539-e1aa785f-8686-428f-b567-1168b1400720.png)

**Comment by kogel-net** [comment]
#255

**Comment by LazyEar0** [comment]
此问题仍存在
![image](https://user-images.githubusercontent.com/95004531/228121353-0cffa2b0-80e9-42b9-a397-028517b932fe.png)
