### ISSUE TITLE
Mouse over the diagram does not match the design

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#206]
鼠标移至图表上的效果与设计稿不符
实际效果：
![image](https://user-images.githubusercontent.com/95004531/226540442-e00ffe66-4ab2-44f1-a1c1-9b6cb5da2b4e.png)
预期效果：
![image](https://user-images.githubusercontent.com/95004531/226540573-5cd62b51-c4ff-4775-83b2-dca42509f4f1.png)

**Comment by Qinyouzeng** [comment]
需要调整 echart json 配置项: tootip 有个属性的 formatter 数字那个，为js 方法，具体参考 echart 文档

**Comment by kogel-net** [comment]
#256

**Comment by LazyEar0** [comment]
此问题仍存在
