### ISSUE TITLE
Dashboards - Default dashboards that lack application details pages

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#207]
仪表盘-缺少应用详情页的默认仪表盘
![image](https://user-images.githubusercontent.com/95004531/226543210-f9fc671f-8549-426f-bdc7-5268c6cb86a1.png)

**Comment by Qinyouzeng** [comment]
需要配置新的仪表盘页面

**Comment by LazyEar0** [comment]
@xie1wei2 请确认需求

**Comment by Qinyouzeng** [comment]
转到 #201
