### ISSUE TITLE
Dashboard list, model does not have i18n

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#208]
仪表盘列表，模型没有i18n
![image](https://user-images.githubusercontent.com/95004531/226543968-5c7ef69f-12c4-4d44-8876-d6390ac7536d.png)
![image](https://user-images.githubusercontent.com/95004531/226544198-2103b79d-8c2b-46f8-a326-5a38b7d775a0.png)

**Comment by kogel-net** [comment]
#256
