### ISSUE TITLE
The indicator expression should be Autocomplete

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#213]
指标表达式应是Autocomplete
![image](https://user-images.githubusercontent.com/95004531/226555318-7a8c7269-eee8-4d85-81ea-dfc0d2969883.png)

**Comment by wuweilaiya** [comment]
AutoComplete 组件bug，需要等组件修复

**Comment by wuweilaiya** [comment]
@capdiem 
https://github.com/BlazorComponent/MASA.Blazor/issues/1130
