### ISSUE TITLE
Indicator expression button position is inconsistent with the design draft

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#214]
指标表达式按钮位置与设计稿不符
实际结果：
![image](https://user-images.githubusercontent.com/95004531/226555474-01ba9626-d3e3-4003-bf83-824601b65264.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/226555777-9dd1dd67-79cb-4404-a398-031f8a2faccd.png)

**Comment by kogel-net** [comment]
#261
