### ISSUE TITLE
Edit dashboard, click the metric expression's Help button, jump to error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#216]
编辑仪表盘，点击指标表达式的帮助按钮，跳转错误
![image](https://user-images.githubusercontent.com/95004531/226556749-d340defb-cacb-4de4-aa76-2d33109dc269.png)

应跳转至MASA Stack文档站点，TSC项目中的解释指标表达式的目录。
参考站点：https://docs.masastack.com/stack/tsc/introduce     具体路径应定位到说明指标表达式的页面

**Comment by zyz** [comment]
#247 Fix: Metrics expression help jump link
