### ISSUE TITLE
Dashboard, tab slider misplaced

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#219]
仪表盘，查看模式下，切换tab，进入编辑模式，tab的滑块错位

https://user-images.githubusercontent.com/95004531/226563750-8883fca6-6c6b-4d68-8feb-53ec80ac5ef1.mp4

**Comment by wuweilaiya** [comment]
@capdiem

**Comment by capdiem** [comment]
@wuweilaiya 需要调 Tabs 引用的 CallSlider 方法。

**Comment by LazyEar0** [comment]
编辑模式下，切换至查看模式，滑块仍错位
![image](https://user-images.githubusercontent.com/95004531/228121819-f79e458f-8575-4ea2-b03c-37c1e92ff56c.png)
