### ISSUE TITLE
Dashboard, model is "All", edit chart, should not show "Item" drop-down box

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#221]
仪表盘 ，模型为“全部”，编辑图表，应不显示“项目”下拉框
![image](https://user-images.githubusercontent.com/95004531/226566268-29e6c2c6-8842-4ede-a1e6-cc2b0d74d199.png)

**Comment by wuweilaiya** [comment]
@xie1wei2

**Comment by xie1wei2** [comment]
这里默认选中前服务，后期做可以切换仪表盘功能。本期选中不可修改。
