### ISSUE TITLE
When editing the dashboard, editing the chart component, switching the time selector, the data in the table does not change based on the selected time period

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#224]
编辑仪表盘，编辑图表组件时，切换时间选择器，表中的数据没有根据所选时间段发生变化
![image](https://user-images.githubusercontent.com/95004531/226787900-16fe13f1-e7ee-48b1-b614-6ed84207db89.png)
![image](https://user-images.githubusercontent.com/95004531/226787966-921a964f-ae61-46ad-b20d-359362b15ef7.png)

**Comment by Qinyouzeng** [comment]
同 toplist 数据加载问题
