### ISSUE TITLE
After the dashboard configuration is complete, save the configuration and view the dashboard, data is missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#225]
仪表盘配置完成，保存后，查看仪表盘，数据缺失
仪表盘模型：全部
![image](https://user-images.githubusercontent.com/95004531/226788783-eb0dbd4a-66ae-45e7-95ed-5223d07d9779.png)
![image](https://user-images.githubusercontent.com/95004531/226788810-83ff800a-addd-40a9-bd02-96da26029f20.png)

**Comment by Qinyouzeng** [comment]
同 #226
