### ISSUE TITLE
TopList cannot obtain the data of the indicator expression

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#226]
TopList 获取不到指标表达式的数据
![image](https://user-images.githubusercontent.com/95004531/226795262-ca81cd56-086e-42dd-aa80-a30176864a7d.png)

**Comment by Qinyouzeng** [comment]
这边操作步骤为：编辑仪表盘，原来是其他类型的pannel，更改类型为toplist,表达式结果有数据返回，ui没有展示

**Comment by Qinyouzeng** [comment]
跟仪表盘配置获取数据的方式有关，一个即时查询，一个历史时间区间查询，需要按实际结果统一确认调整
