### ISSUE TITLE
The close button of the indicator expression should only return to the indicator drop down box

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#230]
指标表达式的关闭按钮，应仅返回至指标下拉框。现点击返回指标下拉框的同时，清空了指标表达式输入框
![image](https://user-images.githubusercontent.com/95004531/226813457-563a117e-53e3-4c3a-9bbd-e9e3a7737493.png)

**Comment by wuweilaiya** [comment]
如果这个输入的值在下拉框中没有的话，就会清空，这个逻辑是对的，因为这两个其实是共享一个值

**Comment by LazyEar0** [comment]
产品需求，这个关闭按钮只返回至下拉框，不清空已输入的值；如果下拉框中选中某一选项，则该选项的值覆盖这个输入框的值，如果下拉框没有选中选项，则不会清空输入框的值。

**Comment by xie1wei2** [comment]
确认，特别是效果请还原设计稿中的效果。

**Comment by wuweilaiya** [comment]
@doddgu confirm

**Comment by doddgu** [comment]
可以把 x 换成 返回的icon。这样更容易理解，x的确容易让人以为是要清空内容。
