### ISSUE TITLE
Full model dashboard, click service, ULRL changes, page does not respond

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#232]
全部模型的仪表盘，点击服务，ULRL发生变化，页面无反应。点击其他菜单也无反应
![image](https://user-images.githubusercontent.com/95004531/226814653-575aa841-c2df-4077-b01a-ea949b6da348.png)

**Comment by Qinyouzeng** [comment]
跳转链接获取问题，已修复
