### ISSUE TITLE
Instance/interface dashboard, instance data display is incomplete

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#235]
实例/接口的仪表盘，实例数据显示不全
![image](https://user-images.githubusercontent.com/95004531/226822494-d7423c1b-dfd9-44e0-8885-763580b80e62.png)

**Comment by LazyEar0** [comment]
这个下拉框是Autocomplete，具体实现效果以 @xie1wei2  需求为准

**Comment by Qinyouzeng** [comment]
我理解是宽度不够，字符串无法全部展示，具体再确认下
可分配

**Comment by xie1wei2** [comment]
固定长度，超出部分用...省略号代替。增加鼠标悬浮效果可以展示全部名称并可以复制！！！（如同Trace后面的可复制效果）

**Comment by xie1wei2** [comment]
![image](https://user-images.githubusercontent.com/101324746/228122795-eca39fae-6573-454a-960d-c230c23a6937.png)

**Comment by LazyEar0** [comment]
缺少tooltips，具体请参考Trace页
![image](https://user-images.githubusercontent.com/95004531/228808270-c5c6259c-814c-42a9-961f-867c86aef389.png)
