### ISSUE TITLE
Interface model dashboard, instance drop-down box should not show "all"

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#236]
接口模型的仪表盘，实例下拉框不应显示“全部”
![image](https://user-images.githubusercontent.com/95004531/226822818-1ab2cd8b-b323-43b5-9a07-4c40230e47c0.png)

**Comment by xie1wei2** [comment]
![image](https://user-images.githubusercontent.com/101324746/227852816-8ab6a3ec-370e-4da9-928a-5e189a9f3a57.png)
1.默认显示第一个实例，不需要显示全部。（实例是可搜索的下拉选择框）
2.关于显示问题，最终由设计为准
3.选中以后，增加鼠标悬浮可以查看完成选中的名称（最好可以有复制按钮）

**Comment by xie1wei2** [comment]
追踪页面，仪表详情中也有类似的框口

**Comment by xie1wei2** [comment]
![image](https://user-images.githubusercontent.com/101324746/227857966-d07cdb1f-d991-4a10-8565-e39b840b9f87.png)

**Comment by xie1wei2** [comment]
![image](https://user-images.githubusercontent.com/101324746/227858147-8a5ffec8-c474-4978-b3e6-15ce38c82d55.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by Qinyouzeng** [comment]
该问题是否可以合并到 #235 @LazyEar0
