### ISSUE TITLE
After the drop-down box is selected, open the drop-down box again, and the selected data is still displayed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#237]
下拉框选中后，再次打开下拉框应仍显示已选中的数据且为选中状态。现再次打开下拉框会过滤选中的数据
![image](https://user-images.githubusercontent.com/95004531/226824352-4af6384c-7168-45c4-ba38-c50c5979b088.png)

**Comment by Qinyouzeng** [comment]
@wuweilaiya

**Comment by LazyEar0** [comment]
需求参考 #236 的评论
