### ISSUE TITLE
Invalid search box in Trace details

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#242]
Trace详情中搜索框无效
![image](https://user-images.githubusercontent.com/95004531/226844001-b28b5f51-a332-453b-883a-17085b726654.png)
预期结果：
此处应为Traceid搜索框，获取当前服务下所有Traceid，支持Autocomplete，默认填充Trace列表选中的Traceid。修改Traceid后，页面数据随之发生变化

**Comment by LazyEar0** [comment]
@xie1wei2

**Comment by xie1wei2** [comment]
搜索框去掉
