### ISSUE TITLE
Trace list, after paging, filter service, pager data error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#244]
Trace列表，翻页后，再过滤服务，分页器数据错误
![image](https://user-images.githubusercontent.com/95004531/226850902-b5a6b45b-cae0-4f00-a7dd-5ac7a67057b2.png)

**Comment by xyfy** [comment]
Processing

**Comment by xyfy** [comment]
改为  @Qinyouzeng 处理
