### ISSUE TITLE
Trace details, hover mouse missing tooltips

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#248]
Trace详情，鼠标悬浮缺少tooltips
![image](https://user-images.githubusercontent.com/95004531/226856558-adfb394a-f3b3-4381-8bb7-48cd5ee967f3.png)

**Comment by MayueCif** [comment]
每个tab中的内容都要添加tooltip,内容显示不全的 都需要加tooltip

**Comment by zyz** [comment]
#259 Tabs item add ToolTips
