### ISSUE TITLE
Some Trace details are displayed, and the page is blank. After waiting, an error message is displayed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#273]
进入部分Trace详情，页面空白，等待后，报错
![企业微信截图_16799692832386](https://user-images.githubusercontent.com/95004531/228109489-fc74c0d0-f89a-46f8-a807-7377c9597f22.png)

**Comment by Qinyouzeng** [comment]
空白情况：
    trace 数据没有链路的头，无法找出根，现在指定按时间最早的一条，部分数据出现存在两条相同的数据的情况

报错的还没复现，应该跟trace 数据量太多有关，目前最多展示9999条，导致内存不足

**Comment by Qinyouzeng** [comment]
现在已经改为 最多1000条，长连接的问题还有问题

**Comment by xie1wei2** [comment]
长链接问题放Rc1以后处理
