### ISSUE TITLE
After clicking the Close button, the input box is misplaced

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#277]
点击关闭按钮后，输入框错位
![image](https://user-images.githubusercontent.com/95004531/228113901-9b8e68f1-102f-4eb5-aebe-0eb11a6f4dca.png)
![image](https://user-images.githubusercontent.com/95004531/228114046-96755a6e-da8a-4821-91be-88b13a86c6c5.png)

**Comment by wuweilaiya** [comment]
@kogel-net
