### ISSUE TITLE
Please check whether the whole TSC project i18n conforms to the specifications and test by yourself

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#278]
英文状态下，仪表盘部分文本缺失。  请自查整个TSC项目 i18n是否符合规范并自测。全部检查完毕后将此issue标记为已解决。
![image](https://user-images.githubusercontent.com/95004531/228115689-2144d661-4a6d-408d-a37d-a10a44a7e9a0.png)

**Comment by Qinyouzeng** [comment]
全部统一按照模块调整，其它模块同样存在该问题

**Comment by Qinyouzeng** [comment]
仪表盘列表有遗漏
