### ISSUE TITLE
An error occurred entering the project details page

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#297]
进入项目详情页报错
![image](https://user-images.githubusercontent.com/95004531/228759165-f44e38bd-28c1-4592-b33e-67a8b0187eb9.png)

![image](https://user-images.githubusercontent.com/95004531/228758399-1d839e18-bd9a-4977-ae06-7081f10931d0.png)
[masa-tsc-service-5bc98d8b4d-t4bqx_masa-tsc-service.log](https://github.com/masastack/MASA.TSC/files/11108841/masa-tsc-service-5bc98d8b4d-t4bqx_masa-tsc-service.log)

**Comment by Qinyouzeng** [comment]
该问题本地未复现，错误信息推测：
- 时间初始化为空值
-  api 返回空结果
发现的bug已修复，有该页面的问题，目前该页面测试结果正常，无错误
