### ISSUE TITLE
Service data is inconsistent

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#303]
模型为全部的仪表盘，Service数据与模型为服务的仪表盘，Service数据不一致
![image](https://user-images.githubusercontent.com/95004531/228800005-27fd0cec-e825-4a7a-bdc3-9e8bcb239a5a.png)
![image](https://user-images.githubusercontent.com/95004531/228800135-41ed9aa4-4dec-4787-9532-ecf6d5ac25fa.png)

**Comment by Qinyouzeng** [comment]
1. all 里面显示的service 列表为 指标的的原始数据；
service 、endpoint 和instacne 仪表盘的服务下拉框为 PM的服务数据和指标的原始数据混合（text: PM 服务名称 (无对应的数据则显示指标原始数据)，Value：指标原始数据）；

2. 如果要保持一致，则仪表盘的服务数据需要进行转化，改转化跟具体的指标查询表达式有关，目前不容易实现；

3. 仪表盘的下拉列表改为显示 应用Id就会保持一致，实现相对简便。

**Comment by LazyEar0** [comment]
@xie1wei2 请确认需求
