### ISSUE TITLE
Translation display problem

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#315]
团队首页

语言切换以后，右侧文字内容不能直接翻译。鼠标滑动到位置以后才会显示内容。

https://user-images.githubusercontent.com/101324746/229671786-7b8bb7ac-48b7-4589-aa22-32776bbac9f7.mp4

**Comment by xie1wei2** [comment]
@MayueCif

**Comment by xie1wei2** [comment]
分配

**Comment by Qinyouzeng** [comment]
已修复，组件更新后，tsc未及时更新
