### ISSUE TITLE
Content coverage problem

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#318]
问题位置：项目详情-点击首页六边形项目中的应用程序后弹出框
<img width="242" alt="image" src="https://user-images.githubusercontent.com/101324746/229673299-bf5f5894-d25d-450f-8f30-7888b460ce2d.png">
当应用名称长度过长的时候出现该遮挡问题

**Comment by xie1wei2** [comment]
@MayueCif 分配

**Comment by MapleWithoutWords** [comment]
![image](https://user-images.githubusercontent.com/38368335/229751834-25681922-6b10-48a3-9c02-0637ad76a51b.png)
already resolved
