### ISSUE TITLE
Project details should be marked "Number of applications"

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#32]
项目详情，应标注“应用数量”
![image](https://user-images.githubusercontent.com/95004531/211956609-a3191847-9582-4762-88d9-99ba1f8ec475.png)

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by 15168440402** [comment]
@xie1wei2

**Comment by LazyEar0** [comment]
样式太丑了，沟通UI重新调整页面 @xie1wei2 
![image](https://user-images.githubusercontent.com/95004531/212457635-fe3915b3-f839-45ad-8268-466a9ab7e521.png)
