### ISSUE TITLE
Chart style problem

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#323]
问题位置：项目详情-点击首页六边形项目中的应用程序后弹出框
<img width="203" alt="image" src="https://user-images.githubusercontent.com/101324746/229674965-021ca8aa-17e6-4b0e-8461-cdd5f4da57df.png">
设计稿
<img width="173" alt="image" src="https://user-images.githubusercontent.com/101324746/229674991-984da094-0894-4a2a-8437-dbdc2d99d1c9.png">
样式需要细微调整，数值大小需要按照设计字体大小来。
数值与单位之间有空格

**Comment by xie1wei2** [comment]
@MayueCif 分配

**Comment by MapleWithoutWords** [comment]
https://github.com/masastack/MASA.Stack.Components/issues/472
