### ISSUE TITLE
Index editing problem

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#327]
表达式组件填写
![image](https://user-images.githubusercontent.com/101324746/229676628-e105469f-b9af-408e-a552-83bb15681f05.png)
如图，有线段格挡。

**Comment by xie1wei2** [comment]
@MayueCif 分配

**Comment by wuweilaiya** [comment]
@capdiem

**Comment by capdiem** [comment]
Masa Blazor 哪个版本？

**Comment by xie1wei2** [comment]
是否可以解决
