### ISSUE TITLE
Tab unable to save

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#343]
![image](https://user-images.githubusercontent.com/101324746/230528180-1f22709d-482f-41ec-b2a9-f3f42bbd898f.png)
在仪表盘中开启编辑模式，Tab增加新的标签后，不增加内容。保存就出现报错！

**Comment by MapleWithoutWords** [comment]
无法复现

**Comment by Qinyouzeng** [comment]
文本框的内容长度超出，文本框内容为html，编辑较多的内容会存在长度超出的问题，该字段数据库长度为2000，如果需要不限长度，需要更改数据类型

**Comment by xie1wei2** [comment]
50个汉字以内

**Comment by MapleWithoutWords** [comment]
我这边给属性增加验证，没有生效。Masa.Blazor没有触发校验：https://github.com/masastack/MASA.Blazor/issues/1211

**Comment by Qinyouzeng** [comment]
跟json 序列化有关 例如 " 变为 \u002
