### ISSUE TITLE
Color not selected

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#351]
![image](https://user-images.githubusercontent.com/101324746/230836131-50456aba-d572-4f4b-aab1-67ead02f0e6d.png)
图表编辑中选择饼图，配置指标以后未随机选中颜色。必须手动颜色以后才会出现。可以提前随机颜色，默认有选中颜色不能为空。
饼图不需要x轴和y轴

**Comment by Qinyouzeng** [comment]
饼图颜色只能显示第一个的颜色
