### ISSUE TITLE
Horizontal line problem

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#352]
![image](https://user-images.githubusercontent.com/101324746/230836873-a85893c0-ce43-4cbd-83c3-b77181840e3a.png)
图标编辑中，选中第一个
第一排横线有2个向上的角度。保存以后展示效果也是有显示2个角度

**Comment by MapleWithoutWords** [comment]
需要等待Stack.Component发布：https://github.com/masastack/MASA.Stack.Components/pull/487
