### ISSUE TITLE
Pressure gauge problem

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#353]
![image](https://user-images.githubusercontent.com/101324746/230837662-f93b984d-f9d8-424f-af89-27fa49976ed8.png)
1.配置完毕，颜色提前默认有一个颜色。不然什么都没
2.不需要再增加指标，这里只能显示一个指标
3.压力表显示为百分比
4.上面不需要有颜色介绍，而且显示的是英文Pressure 默认去掉
5.不需要x轴和y轴
6.保存展现名称与数值有遮挡

**Comment by Qinyouzeng** [comment]
饼图颜色只能显示第一个的颜色
