### ISSUE TITLE
Add sequence problem

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#355]
![image](https://user-images.githubusercontent.com/101324746/230844123-684918c9-b60e-4810-804c-6dc545b55e9e.png)
按照添加顺序，以及效果
有2个实现方案，根据开发难度选择简易
1.按照图中顺序，最后添加的卡片再最上面。
2.锚点定位至最近添加的卡片
问题效果：如果卡片超过9个或者超过一页。再添加卡片的时候出现在下面，就不知道添加在哪会造成无限点击找不到的情况！

**Comment by MayueCif** [comment]
方案1
