### ISSUE TITLE
团队详情页，服务选择切换问题

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#357]
![image](https://user-images.githubusercontent.com/101324746/230854928-f10662ce-df1b-4901-9fb2-d9c6d4543a81.png)
如图，服务切换会直接关闭弹窗。正常应该是显示对应服务的内容

**Comment by capdiem** [comment]
may be the same problem as masastack/MASA.Blazor#1199

**Comment by doddgu** [comment]
已经合并尝试修复
