### ISSUE TITLE
仪表盘卡片居中问题

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#381]
![企业微信截图_16813663916433](https://user-images.githubusercontent.com/101324746/231670076-602a7206-993a-4913-a244-036960fbfa32.png)
内容未居中

**Comment by MapleWithoutWords** [comment]
已居中，4k和1920显示效果如下
![image](https://user-images.githubusercontent.com/38368335/231680853-e9609b86-fa69-42a5-be3c-c8efd641168c.png)
![image](https://user-images.githubusercontent.com/38368335/231680931-fd7690d7-a3fa-4096-9590-a805ceedef9a.png)
