### ISSUE TITLE
Trace详情页

### ISSUE THREAD

**Issue by Qinyouzeng** [masastack/MASA.TSC#405]
1.团队首页，点击服务进入团队详情页，最下面右边的慢接口，点击后的跳转调整：
     当前 先调用获取traceId的接口，再跳转到trace 详情页 ；
     调整为： 先跳转到 trace详情页，再获取traceId，最后加载详情数据；

2.trace 详情页ui展示调整
    tree 参考
    
![image](https://user-images.githubusercontent.com/102203523/233831354-7b9833d2-1aa1-4df1-9378-8668fd0056d8.png)

右边卡片信息也参考上图，重要信息也参考上图，适应4K屏幕

trace 数据结构详细文档由@qinyouzeng提供
[trace数据样例和说明.txt](https://github.com/masastack/MASA.TSC/files/11305473/trace.txt)

**Comment by xie1wei2** [comment]
http  数据库  错误 3个标签

**Comment by xie1wei2** [comment]
http:颜色代码 E9E2FC 
Error：颜色代码 FFDBDC
数据库：DCFFDB

**Comment by xyfy** [comment]
右侧效果
![image](https://user-images.githubusercontent.com/7838147/234155038-06d6afe7-db36-4472-a31a-6d79a0ae1146.png)
