### ISSUE TITLE
慢接口点击后弹出时间缓慢

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#406]
慢接口点击后团出时间缓慢，提升用户体验。用骨架屏来增加用户体验。消除原来点击以后没有任何反应的尴尬场景。
点击以后弹出骨架，数据可以加载中。

**Comment by MayueCif** [comment]
重构SheetDialog,弹窗立刻弹出，显示骨架

**Comment by xyfy** [comment]
最终讨论决定，不使用骨架，使用了Progress circular（进度环）

**Comment by xyfy** [comment]
这个跟  #405 有一定重叠。tsc部分代码放一个pr #424  里提交
