### ISSUE TITLE
仪表盘-仪表盘保存后对仪表盘内的指标进行计算

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#409]
所有保存仪表盘以后，对仪表盘内容指标进行计算。计算完成后弹出保存成功的提示。未完成前可以有保存的耗时。

**Comment by Qinyouzeng** [comment]
该方案存在问题，对查询表达式解析进行了缓存，首次执行会慢一点，第二次之后会正常；缓存过期时间暂时设置为6h
