### ISSUE TITLE
仪表盘-修改仪表盘保存以后点击展示效果，出现的二次确认弹窗样式修改

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#413]
![image](https://user-images.githubusercontent.com/101324746/233835877-58554a26-e9e2-433a-a1e4-759d73dc7d8f.png)
修改为设计稿中的新样式
![image](https://user-images.githubusercontent.com/101324746/233836207-3a1b6e23-0602-4221-a7e9-4983b79aa8c5.png)

**Comment by kogel-net** [comment]
https://github.com/masastack/MASA.Stack.Components/pull/572
