### ISSUE TITLE
仪表盘-卡片边框颜色修改

### ISSUE THREAD

**Issue by xie1wei2** [masastack/MASA.TSC#415]
![image](https://user-images.githubusercontent.com/101324746/233836529-53bf4c66-f3fc-429b-b218-b3cd08e9ed84.png)
颜色修改为：E1E3EA

**Comment by xyfy** [comment]
这个是tsc集成的组件，跟 @xie1wei2  确认，在组件上修改样式，不单单只为dashbord页面修改。
