### ISSUE TITLE
The dashboard set to root is not displayed in the left menu

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#44]
设为根的仪表盘没有显示在左侧菜单中
![image](https://user-images.githubusercontent.com/95004531/211974314-29da007b-b43d-44eb-be04-7436508edc7a.png)

**Comment by Qinyouzeng** [comment]
@xie1wei2 确认下

**Comment by xie1wei2** [comment]
设为根以后是需要显示在左侧的

**Comment by Qinyouzeng** [comment]
左侧菜单如何显示：
1. 固定添加到仪表盘目录；
2. 根据需求，例如数据库的仪表一，左侧就创建 数据库->仪表盘一的菜单，再添加数据库的仪表盘二，就自动在数据库目录下创建仪表二菜单？

**Comment by xie1wei2** [comment]
当设为根的时候显示在左侧，如果当一个文件夹中有大于一个仪表盘被设为根，则左侧显示文件夹名称然后有二级分别是两个仪表盘的名称

**Comment by Qinyouzeng** [comment]
目录下只有一个root仪表盘时，直接显示为顶级菜单，有多个root时，先展示目录，再展示root仪表盘。
新建一个目录，新建一个root仪表盘，只创建菜单，不创建目录；
再添加一个root的仪表盘，菜单新增一个目录，然后把这两个菜单添加到这个目录下；
如果删除或取消了一个root仪表盘，就把目录删除，同时剩余的那一个root仪表盘目录设置为空；
这个逻辑吗？

**Comment by LazyEar0** [comment]
1.0.0 没有“设为根”需求
