### ISSUE TITLE
中文模式下， 建议指标字段改为中文

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.TSC#452]
![image](https://github.com/masastack/MASA.TSC/assets/93168234/2d933498-2605-48bd-aee2-cf41dc7109f8)

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.TSC/assets/93168234/4cc72f08-a621-48ce-9a6c-70c5b504cf99)

**Comment by Qinyouzeng** [comment]
目前指标不支持i8n
