### ISSUE TITLE
仪表盘，trace  筛选和查询，UI优化

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.TSC#458]
![image](https://github.com/masastack/MASA.TSC/assets/93168234/06de6295-b997-472b-b7c1-d099096cf72d)

**Comment by limei7** [comment]
![image](https://github.com/masastack/MASA.TSC/assets/93168234/a1a315d5-222a-4beb-afb2-63d0a57ddca2)

**Comment by Qinyouzeng** [comment]
仪表盘内的内容当前不在优化范围之内
