### ISSUE TITLE
Dashboard, Echarts, table chart, drop down box is the item drop down box

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#50]
仪表盘，Echarts，table图表，下拉框为项目下拉框，显示监测的项目，选中之后对Tsc其他页面没有影响
![image](https://user-images.githubusercontent.com/95004531/211981264-ff26a92b-7cd6-4f04-9a95-db8eee7c0fb8.png)

**Comment by LazyEar0** [comment]
@xie1wei2  显示哪些项目，是否要过滤，需求要确认一下

**Comment by LazyEar0** [comment]
> @xie1wei2 显示哪些项目，是否要过滤，需求要确认一下

@xie1wei2  请确认需求，“项目”下拉框是否需要

**Comment by xie1wei2** [comment]
隐藏掉，暂时不需要！后面是用来切换仪表盘用
