### ISSUE TITLE
Dashboard, services in the Echarts component are filtered based on the application of the dashboard detail page

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#65]
仪表盘，Echarts组件中服务根据仪表盘详情页的应用进行过滤，All模型的仪表盘则显示所有服务 
![image](https://user-images.githubusercontent.com/95004531/212003037-8db3c4f9-93f3-4b5f-aac0-64c1956f2da3.png)
![image](https://user-images.githubusercontent.com/95004531/212003064-1a9d36ab-8e54-4b50-b1f9-2ca197cd2d1b.png)

**Comment by LazyEar0** [comment]
ALL ： ServiceList 和TopList
Service ： EndpointList 和 InstanceList，和TopList
ServiceInstance ：只有TopList
Endpoint ：只有TopList

**Comment by Qinyouzeng** [comment]
ServiceInstance ：有 EndpointList 和  TopList
