### ISSUE TITLE
Dashboard, Echarts component requirements perfect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#68]
仪表盘，Echarts组件，Options 中 Enable pagination 需求完善 #67

**Comment by Qinyouzeng** [comment]
@xie1wei2  当前 table 组件是否需要支持分页配置

**Comment by Qinyouzeng** [comment]
1. 当前列表不支持分页，用户是通过指标表达式来确定数据的条数，类似top n,查询结果有多少展示多少，因为指标查询不支持分页，只能全部查询出来，由页面来控制每页显示条数，该功能确认也需要支持吗？；
2. table 功能有分页，但是当前没有设置分页大小的，目前是固定的，这个是否支持配置分页大小？
