### ISSUE TITLE
The Table component function of the dashboard is missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#79]
仪表盘，Table组件功能缺失 
![image](https://user-images.githubusercontent.com/95004531/212007392-e9cd61ce-aba0-41a6-9990-56ffb55ff9ad.png)

**Comment by Qinyouzeng** [comment]
当前table只支持 service list，instance list endpoint list 和 top list

**Comment by LazyEar0** [comment]
> 当前table只支持 service list，instance list endpoint list 和 top list 确认下入口是否需要放在外面，当前入口是和Echart图标一起

@xie1wei2 请知晓
