### ISSUE TITLE
When you enter the Dashboard Details page and click the back button of the page, you cannot return to the dashboard list

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#82]
仪表盘进入仪表盘详情页，点击网页的后退按钮，无法返回至仪表盘列表
![image](https://user-images.githubusercontent.com/95004531/212009661-b739b0dc-9c67-4d85-8157-fa2a5703d232.png)

**Comment by MayueCif** [comment]
尝试用js监听浏览器回退按钮事件
