### ISSUE TITLE
The Log page is inconsistent with the UI

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#86]
Log页面与UI不一致
实际效果：
![image](https://user-images.githubusercontent.com/95004531/212014493-354ecf42-c0d4-42e1-a4b1-02a28218e68f.png)
预期结果：
![image](https://user-images.githubusercontent.com/95004531/212014798-85ec0c0a-4b07-4060-82e9-2585792287e2.png)

**Comment by xie1wei2** [comment]
UI设计已经修改过了

**Comment by LazyEar0** [comment]
@xie1wei2   实际效果是否有“换行”开关，如有，请明确需求。
![image](https://user-images.githubusercontent.com/95004531/225242652-3b58e2e7-f600-43df-8a2c-02320842a81b.png)
