### ISSUE TITLE
Dashboard, Echarts component, set column text color function missing

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#91]
仪表盘，Echarts组件，设置列文本颜色功能缺失。具体需求 @xie1wei2  请完善
![image](https://user-images.githubusercontent.com/95004531/212022051-15210736-6019-4a50-8895-6420bb3d8114.png)

**Comment by xie1wei2** [comment]
颜色需要补充，该颜色选择对应图表中的线条颜色。list的4个表格中不需要设置颜色选择
