### ISSUE TITLE
Dashboard, Echarts component, click row, page data error

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#92]
仪表盘，Echarts组件，点击行，清空当前编辑的组件，增加一个新的Tab和Text组件
![image](https://user-images.githubusercontent.com/95004531/212024527-3e826e9c-725c-4f01-aa86-18f89ceffe4d.png)
![image](https://user-images.githubusercontent.com/95004531/212024796-28c0769a-448c-4d41-80b8-172e20dde4b0.png)

**Comment by 15168440402** [comment]
这是页面跳转了

**Comment by LazyEar0** [comment]
编辑仪表盘页，Table组件的行不可以跳转
