### ISSUE TITLE
Instrument panel, component enlargement shall have maximum size

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#93]
仪表盘，组件放大应有最大尺寸，内部图表拖拽，应在组件尺寸范围内拖拽，不加滚动条
![image](https://user-images.githubusercontent.com/95004531/212025265-02b1b710-adef-48da-af6b-8e1e8e1f8dc0.png)

**Comment by 15168440402** [comment]
滚动条已去，拖拽范围无法解决

**Comment by LazyEar0** [comment]
@xie1wei2  请确认拖拽范围是否需要限制

**Comment by xie1wei2** [comment]
50%-250%区间内，最大不超过250%
