### ISSUE TITLE
Log, we're missing units on the vertical chart

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.TSC#95]
Log，图表纵坐标缺少单位
![image](https://user-images.githubusercontent.com/95004531/212028053-ca7a2972-be5d-480e-9cb0-2102adc0e6b1.png)

**Comment by Qinyouzeng** [comment]
单位为：条，已经添加

**Comment by LazyEar0** [comment]
此问题仍存在
![image](https://user-images.githubusercontent.com/95004531/223912060-61249064-98f3-427e-bacc-1342e6c247a2.png)

**Comment by Qinyouzeng** [comment]
Not issue
